#!/bin/bash

echo "🔧 Backend CORS Configuration Fix"
echo "=================================="
echo ""

echo "📋 Changes made to backend:"
echo "  ✅ Enhanced CORS configuration to allow all Vercel deployments"
echo "  ✅ Added global OPTIONS handler for preflight requests"
echo "  ✅ Added comprehensive CORS headers"
echo "  ✅ Added test endpoint: /api/test-cors"
echo "  ✅ Updated SERVER_URL to https://api.banhannah.dpdns.org"
echo ""

echo "🚀 To deploy these changes to Oracle Cloud:"
echo ""
echo "1. SSH to your Oracle Cloud instance:"
echo "   ssh your-username@your-server-ip"
echo ""
echo "2. Navigate to your backend directory:"
echo "   cd /path/to/your/backend"
echo ""
echo "3. Pull the latest changes:"
echo "   git pull origin main"
echo ""
echo "4. Restart the backend service:"
echo "   # If using PM2:"
echo "   pm2 restart all"
echo "   # Or if using systemd:"
echo "   sudo systemctl restart your-app-name"
echo "   # Or if running directly:"
echo "   pkill -f node && nohup npm start > app.log 2>&1 &"
echo ""
echo "5. Test the CORS fix:"
echo "   curl -H \"Origin: https://banhannah.vercel.app\" https://api.banhannah.dpdns.org/api/test-cors"
echo ""
echo "6. Test preview image endpoint:"
echo "   curl -I -H \"Origin: https://banhannah.vercel.app\" https://api.banhannah.dpdns.org/api/files/preview/1769304398900_btkeyb_unnamed__2_.jpg"
echo ""

echo "🔍 Expected results:"
echo "  - CORS test should return JSON with success message"
echo "  - Preview image should return 200 OK with proper CORS headers"
echo "  - Access-Control-Allow-Origin header should be present"
echo ""

echo "🌐 After backend deployment, redeploy frontend:"
echo "   cd frontend && npm run build && vercel --prod"
echo ""

echo "✅ This should fix the ERR_BLOCKED_BY_RESPONSE.NotSameOrigin error!"