#!/bin/bash

echo "🚀 Deploying Backend Changes to Oracle Cloud"
echo "============================================"
echo ""

echo "📋 Steps to deploy:"
echo ""
echo "1. First, commit and push the changes to your git repository:"
echo "   git add ."
echo "   git commit -m 'Fix CORS issues for preview images'"
echo "   git push origin main"
echo ""
echo "2. SSH to your Oracle Cloud instance:"
echo "   ssh ubuntu@instance-20260125-0154"
echo ""
echo "3. Navigate to your backend directory:"
echo "   cd /var/www/banhannah/backend"
echo ""
echo "4. Pull the latest changes:"
echo "   git pull origin main"
echo ""
echo "5. Check if there are any new dependencies:"
echo "   npm install"
echo ""
echo "6. Restart the backend service:"
echo "   # Check what process manager you're using:"
echo "   ps aux | grep node"
echo "   # If using PM2:"
echo "   pm2 restart all"
echo "   # If using systemd:"
echo "   sudo systemctl restart your-service-name"
echo "   # If running with nohup:"
echo "   pkill -f 'node.*server.js' && nohup npm start > app.log 2>&1 &"
echo ""
echo "7. Verify the deployment:"
echo "   curl https://api.banhannah.dpdns.org/health"
echo "   curl -H \"Origin: https://banhannah.vercel.app\" https://api.banhannah.dpdns.org/api/test-cors"
echo ""

echo "🔧 Key files that were changed:"
echo "  - backend/src/app.js (CORS configuration)"
echo "  - backend/src/controllers/files.controller.js (enhanced CORS headers)"
echo "  - backend/src/routes/files.routes.js (OPTIONS handler)"
echo "  - backend/src/services/storage.service.js (absolute URLs)"
echo "  - backend/.env.production (SERVER_URL fix)"
echo ""

echo "✅ After successful deployment, test with:"
echo "   curl -H \"Origin: https://banhannah.vercel.app\" https://api.banhannah.dpdns.org/api/test-cors"
echo ""
echo "Expected response:"
echo '   {"message":"CORS test successful","origin":"https://banhannah.vercel.app",...}'